/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package HospitalManagementSystem;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Adarsh Maurya
 */
public class Activity_11 extends javax.swing.JFrame {
String path="";
    /**
     * Creates new form Activity_11
     */
    public Activity_11() {
        initComponents();
        getContentPane().setBackground(new Color(153,153,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkwed = new javax.swing.JCheckBox();
        checkmon = new javax.swing.JCheckBox();
        txt_salary = new javax.swing.JTextField();
        txt_dateofjoin = new javax.swing.JTextField();
        checksun = new javax.swing.JCheckBox();
        txtcontacts = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_specialization = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkfri = new javax.swing.JCheckBox();
        checkthu = new javax.swing.JCheckBox();
        checksat = new javax.swing.JCheckBox();
        checktue = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        fc = new javax.swing.JFileChooser();
        jLabel3 = new javax.swing.JLabel();
        txt_empID = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        checkwed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkwed.setText("Wednesday");
        checkwed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkwedActionPerformed(evt);
            }
        });

        checkmon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkmon.setText("Monday");
        checkmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkmonActionPerformed(evt);
            }
        });

        txt_salary.setEditable(false);
        txt_salary.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });

        txt_dateofjoin.setEditable(false);
        txt_dateofjoin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_dateofjoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateofjoinActionPerformed(evt);
            }
        });

        checksun.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checksun.setText("Sunday");

        txtcontacts.setEditable(false);
        txtcontacts.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtcontacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactsActionPerformed(evt);
            }
        });

        txt_name.setEditable(false);
        txt_name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Section");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        lblimage.setText("img");
        lblimage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date of joining");

        txt_specialization.setEditable(false);
        txt_specialization.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_specialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_specializationActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Address");

        txt_address.setEditable(false);
        txt_address.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Contacts");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Salary");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Weekend dates");

        checkfri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkfri.setText("Friday");

        checkthu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkthu.setText("Thursday");

        checksat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checksat.setText("Saturday");

        checktue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checktue.setText("Tuesday");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Nurse Details");

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Search Details");
        jButton6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton6StateChanged(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(0, 0, 0));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit Details");
        btnedit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btneditStateChanged(evt);
            }
        });
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add details");
        jButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton1StateChanged(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnbackStateChanged(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnback)
                .addGap(272, 272, 272)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272)
                .addComponent(jButton6)
                .addGap(35, 35, 35)
                .addComponent(btnedit)
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(btnedit)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton2.setVisible(false);
        jButton2.setText("uploadimage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(false);

        jScrollPane1.setViewportView(fc);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("EmployeeID");

        btnsave.setVisible(false);
        btnsave.setBackground(new java.awt.Color(0, 0, 0));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnsaveStateChanged(evt);
            }
        });
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnsearch.setBackground(new java.awt.Color(0, 0, 0));
        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnsearchStateChanged(evt);
            }
        });
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnadd.setVisible(false);
        btnadd.setBackground(new java.awt.Color(0, 0, 0));
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add");
        btnadd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnaddStateChanged(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_specialization, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txt_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(txt_dateofjoin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(759, 759, 759)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addComponent(checksun)
                .addGap(5, 5, 5)
                .addComponent(checkmon)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(checkwed))
                    .addComponent(checktue))
                .addGap(7, 7, 7)
                .addComponent(checkthu)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(checksat))
                    .addComponent(checkfri)))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(txt_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcontacts, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(txt_specialization, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dateofjoin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton2)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checksun)
                            .addComponent(checkmon)
                            .addComponent(checkwed)
                            .addComponent(checktue)
                            .addComponent(checkthu)
                            .addComponent(checksat)
                            .addComponent(checkfri))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcontacts, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkwedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkwedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkwedActionPerformed

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryActionPerformed

    private void txt_dateofjoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateofjoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateofjoinActionPerformed

    private void txtcontactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactsActionPerformed

    private void txt_specializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_specializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_specializationActionPerformed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void checkmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkmonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkmonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
       FileNameExtensionFilter filter= new FileNameExtensionFilter("JPEG file and PNG file","jpg","jpeg","png");
      fc.setFileFilter(filter);
      int response=fc.showOpenDialog(jInternalFrame1);
      if(response==fc.APPROVE_OPTION){
          path=fc.getSelectedFile().toString();
           ImageIcon img=new ImageIcon(path);
                  lblimage.setIcon(img);
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         
         
        
    }//GEN-LAST:event_formWindowActivated
public void clear(){
         checksun.setSelected(false);
              checkmon.setSelected(false);
              checktue.setSelected(false);
              checkwed.setSelected(false);
              checkthu.setSelected(false);
              checkfri.setSelected(false);
              checksat.setSelected(false);
                txt_name.setText("");
         txt_address.setText("");
          txt_specialization.setText("");
           txt_salary.setText("");
            txt_dateofjoin.setText("");
            txtcontacts.setText("");
            path="";
}
    private void jButton6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton6StateChanged
        // TODO add your handling code here:
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
        btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
        btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
        jButton1.setBackground(Color.black);
        jButton1.setForeground(Color.white);
        jButton6.setBackground(Color.white);
        jButton6.setForeground(Color.black);
    }//GEN-LAST:event_jButton6StateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        clear();
        txt_name.setEditable(false);
        txt_address.setEditable(false);
        txt_specialization.setEditable(false);
        txt_salary.setEditable(false);
        txt_dateofjoin.setEditable(false);
        txtcontacts.setEditable(false);
           txt_empID.setEditable(true);
        jButton2.setVisible(false);
        btnadd.setVisible(false);
        btnsave.setVisible(false);
        btnsearch.setVisible(true);
        txt_empID.setText("");
        ImageIcon img=new ImageIcon("");
        lblimage.setIcon(img);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btneditStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btneditStateChanged
        // TODO add your handling code here:
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
        btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
        btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnedit.setBackground(Color.white);
        btnedit.setForeground(Color.black);
    }//GEN-LAST:event_btneditStateChanged

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        jButton2.setVisible(true);
        btnsave.setVisible(true);
        txt_name.setEditable(true);
        txt_address.setEditable(true);
        txt_specialization.setEditable(true);
        txt_salary.setEditable(true);
        txt_dateofjoin.setEditable(true);
        txtcontacts.setEditable(true);
        txt_empID.setEditable(false);

    }//GEN-LAST:event_btneditActionPerformed

    private void jButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged
        // TODO add your handling code here:
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
        btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
        btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
        jButton6.setBackground(Color.black);
        jButton6.setForeground(Color.white);
        jButton1.setBackground(Color.white);
        jButton1.setForeground(Color.black);
    }//GEN-LAST:event_jButton1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clear();
        txt_empID.setEditable(true);
        txt_name.setEditable(true);
        txt_address.setEditable(true);
        txt_specialization.setEditable(true);
        txt_salary.setEditable(true);
        txt_dateofjoin.setEditable(true);
        txtcontacts.setEditable(true);
        jButton2.setVisible(true);
        btnadd.setVisible(true);
        btnsave.setVisible(false);
        btnsearch.setVisible(false);
        txt_empID.setText("");
        ImageIcon img=new ImageIcon("");
        lblimage.setIcon(img);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbackStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnbackStateChanged
        // TODO add your handling code here:
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
        btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
        btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.white);
        btnback.setForeground(Color.black);
    }//GEN-LAST:event_btnbackStateChanged

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        new Activity_4().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
         btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
          jButton6.setBackground(Color.black);
       jButton6.setForeground(Color.white);
        jButton1.setBackground(Color.black);
       jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void btnsaveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnsaveStateChanged
        // TODO add your handling code here:
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnsave.setBackground(Color.white);
        btnsave.setForeground(Color.black);
    }//GEN-LAST:event_btnsaveStateChanged

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String code="",code1="",checkcode="";String sun="A",mon="A",tue="A",wed="A",thu="A",fri="A",sat="A";
        establishconnection ob=new establishconnection();
        checkcode= "select employeeID from employee;";
        if(txt_empID.getText().equals("")||txt_name.getText().equals("")||txt_address.getText().equals(""))
        JOptionPane.showMessageDialog(null,"please enter the details");
        if(checksun.isSelected()==true)
        sun="P";
        if(checkmon.isSelected()==true)
        mon="P";
        if(checktue.isSelected()==true)
        tue="P";
        if(checkwed.isSelected()==true)
        wed="P";
        if(checkthu.isSelected()==true)
        thu="P";
        if(checkfri.isSelected()==true)
        fri="P";
        if(checksat.isSelected()==true)
        sat="P";
        code1="delete from employee where employeeID='"+txt_empID.getText()+"';";
        code="insert into employee values('"+(txt_empID.getText())+"','"+txt_name.getText()+"','"+txt_specialization.getText()+"','"+txt_address.getText()+"','"+txt_dateofjoin.getText()+"','"+sun+"','"+mon+"','"+tue+"','"+wed+"','"+thu+"','"+fri+"','"+sat+"','"+txt_salary.getText()+"','"+txtcontacts.getText()+"','"+path+"','Nurse');";
        System.out.println(code);
        int flag2=ob.update(code1);
        if(flag2==1){
            int flag=ob.update(code);
            if(flag==1){
                JOptionPane.showMessageDialog(null,"Edited successfully");
                clear();
            }
            else if(flag==0||flag2==0)
            JOptionPane.showMessageDialog(null,"process failed");
        }
        else
        JOptionPane.showMessageDialog(null,"Error");
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnsearchStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnsearchStateChanged
        // TODO add your handling code here:
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
        btnsearch.setBackground(Color.white);
        btnsearch.setForeground(Color.black);
    }//GEN-LAST:event_btnsearchStateChanged

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        clear();
        String code="";String designation="";
        establishconnection ob =new establishconnection();
        if(!(txt_empID.getText().equals(""))){
            code="select * from employee where designation='Nurse' && employeeID='"+txt_empID.getText()+"';";
            System.out.println(code);
            ob.execute(code);
            try{
                while(ob.rs.next()){
                    txt_empID.setText(ob.rs.getString("employeeID"));
                    txt_name.setText(ob.rs.getString("Name"));
                    txt_specialization.setText(ob.rs.getString("specialization"));
                    txt_address.setText(ob.rs.getString("address"));
                    txt_dateofjoin.setText(""+ob.rs.getString("dateofjoin"));
                    if(ob.rs.getString("sunday").equals("P"))
                    checksun.setSelected(true);
                    if(ob.rs.getString("monday").equals("P"))
                    checkmon.setSelected(true);
                    if(ob.rs.getString("Tuesday").equals("P"))
                    checktue.setSelected(true);
                    if(ob.rs.getString("Wednesday").equals("P"))
                    checkwed.setSelected(true);
                    if(ob.rs.getString("Thursday").equals("P"))
                    checkthu.setSelected(true);
                    if(ob.rs.getString("friday").equals("P"))
                    checkfri.setSelected(true);
                    if(ob.rs.getString("Saturday").equals("P"))
                    checksat.setSelected(true);
                    txt_salary.setText(""+ob.rs.getString("salary"));
                    txtcontacts.setText(""+ob.rs.getString("contacts"));
                        String p=ob.rs.getString("img");
                   int n=p.length();
                   String np="";
                   for(int i=0;i<n;i++){
                       if(p.charAt(i)==':'){
                           np+=":\\";
                       }
                       else{
                           np+=p.charAt(i);
                       }
                   }
                   
                    ImageIcon img=new ImageIcon(ob.rs.getString(np));
                    lblimage.setIcon(img);
                    designation=ob.rs.getString("designation");
                }
                if(txt_address.getText().equals(""))
                JOptionPane.showMessageDialog(null,"Not available");
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnaddStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnaddStateChanged
        // TODO add your handling code here:
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
        btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
        btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnadd.setBackground(Color.white);
        btnadd.setForeground(Color.black);
    }//GEN-LAST:event_btnaddStateChanged

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        
        String code="",checkcode="";String sun="A",mon="A",tue="A",wed="A",thu="A",fri="A",sat="A";
        establishconnection ob=new establishconnection();
        checkcode= "select employeeID from employee;";
        try{
            ob.execute(checkcode);
            while(ob.rs.next()){
                if(txt_empID.getText().equalsIgnoreCase(ob.rs.getString("employeeID")))
                JOptionPane.showMessageDialog(null,"EmpID already in use");
            }}
            catch(Exception e){

            }
            if(txt_empID.getText().equals("")||txt_name.getText().equals("")||txt_address.getText().equals(""))
            JOptionPane.showMessageDialog(null,"please enter the details");
            if(checksun.isSelected()==true)
            sun="P";
            if(checkmon.isSelected()==true)
            mon="P";
            if(checktue.isSelected()==true)
            tue="P";
            if(checkwed.isSelected()==true)
            wed="P";
            if(checkthu.isSelected()==true)
            thu="P";
            if(checkfri.isSelected()==true)
            fri="P";
            if(checksat.isSelected()==true)
            sat="P";
            code="insert into employee values('"+(txt_empID.getText())+"','"+txt_name.getText()+"','"+txt_specialization.getText()+"','"+txt_address.getText()+"','"+txt_dateofjoin.getText()+"','"+sun+"','"+mon+"','"+tue+"','"+wed+"','"+thu+"','"+fri+"','"+sat+"','"+txt_salary.getText()+"','"+txtcontacts.getText()+"','"+path+"','Nurse');";
            System.out.println(code);
            int flag=ob.update(code);

            if(flag==1){
                JOptionPane.showMessageDialog(null,"added successfully");
                clear();
                txt_empID.setText("");
            }
            else if(flag==0)
            JOptionPane.showMessageDialog(null,"process failed");

    }//GEN-LAST:event_btnaddActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
         btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
          jButton6.setBackground(Color.black);
       jButton6.setForeground(Color.white);
        jButton1.setBackground(Color.black);
       jButton1.setForeground(Color.white);
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JCheckBox checkfri;
    private javax.swing.JCheckBox checkmon;
    private javax.swing.JCheckBox checksat;
    private javax.swing.JCheckBox checksun;
    private javax.swing.JCheckBox checkthu;
    private javax.swing.JCheckBox checktue;
    private javax.swing.JCheckBox checkwed;
    private javax.swing.JFileChooser fc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_dateofjoin;
    private javax.swing.JTextField txt_empID;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_specialization;
    private javax.swing.JTextField txtcontacts;
    // End of variables declaration//GEN-END:variables
}
